### ISSUE TITLE
Export/import as YAML

### ISSUE THREAD

**Issue by darkr4y** [synfron/ReshaperForBurp#24]
It would be nice if the `whens-thens` workflow (rules and configuration) could be described via **yaml**
the reason:
1. human readable
2. more easier for multiple people to collaborate in a git-based way like the `nuclei-template`

----

The compromise I'm trying at the moment
Write each rule as a yaml,then combine them with python script and convert them into a json file, and the last import the json file into Reshaper
The problem at the moment, the [documentation](https://synfron.github.io/ReshaperForBurp/Rules.html) does not provide the values of all possible keys in all json

A sample rule yaml (converted from json):

```
rules:
- whens:
  - "@class": ".WhenMatchesText"
    negate: false
    useOrCondition: false
    identifier:
      text: ''
      variables: []
    identifierPlacement: Last
    sourceText:
      text: ''
      variables: []
    matchText:
      text: Whitelabel
      variables: []
    messageValue: HttpResponseBody
    messageValueType: Text
    messageValuePath:
      text: ''
      variables: []
    matchType: Contains
    useMessageValue: true
  thens:
  - "@class": ".ThenRunProcess"
    command:
      text: nuclei
      variables: []
    input:
      text: "-u URL_VARIABLE -w spring4shell.yaml"
      variables: []
    waitForCompletion: true
    failAfter:
      text: '5000'
      variables: []
    killAfterFailure: false
    failOnNonZeroExitCode: false
    breakAfterFailure: true
    captureOutput: true
    captureAfterFailure: false
    captureVariableSource: Event
    captureVariableName:
      text: NUCLEI_RESULT
      variables: []
  enabled: false
  autoRun: true
  name: NucleiSpring
variables: []
```

the origin exported json:
```
{"rules":[{"whens":[{"@class":".WhenMatchesText","negate":false,"useOrCondition":false,"identifier":{"text":"","variables":[]},"identifierPlacement":"Last","sourceText":{"text":"","variables":[]},"matchText":{"text":"Whitelabel","variables":[]},"messageValue":"HttpResponseBody","messageValueType":"Text","messageValuePath":{"text":"","variables":[]},"matchType":"Contains","useMessageValue":true}],"thens":[{"@class":".ThenRunProcess","command":{"text":"nuclei","variables":[]},"input":{"text":"-u URL_VARIABLE -w spring4shell.yaml","variables":[]},"waitForCompletion":true,"failAfter":{"text":"5000","variables":[]},"killAfterFailure":false,"failOnNonZeroExitCode":false,"breakAfterFailure":true,"captureOutput":true,"captureAfterFailure":false,"captureVariableSource":"Event","captureVariableName":{"text":"NUCLEI_RESULT","variables":[]}}],"enabled":false,"autoRun":true,"name":"NucleiSpring"}],"variables":[]}
```
