### ISSUE TITLE
Starter HTTP Message headers overwritten when using Message Value Setter: Request Body

### ISSUE THREAD

**Issue by tomdottom** [synfron/ReshaperForBurp#41]
# Steps to reproduce

1. Create a _Starter HTTP Message_ as a global variable with the contents:

```
POST /post HTTP/1.1
Host: 0.0.0.0:9999
Content-Type: application/json
Connection: close
```

![image](https://github.com/synfron/ReshaperForBurp/assets/5106166/b12ecf44-f266-4275-9830-4404433b3b63)

2. Create a new _Rule_  with a _Then_ using `Build HTTP Message: Request`
    - Use the the starter message from step 1.
    - Configure a `Message Value Setter` which sets the `Request Body` to some simple text like _Test_
    - Set the destination variable

3. Add a _Then_ to log the request variable from step 2.

![image](https://github.com/synfron/ReshaperForBurp/assets/5106166/b87155d7-e913-4315-8cf7-86a5bae4b3f3)

4. Send a request through Burp to trigger the _Rule_ then look in the logs.  It should be apparent that the `Host` and `Content-Type` headers from the starter message have been removed:

```
POST /post HTTP/1.1
Content-Length: 4

Test
```

![image](https://github.com/synfron/ReshaperForBurp/assets/5106166/9587389d-eee5-43b4-9ead-3631b9f8eb83)

# Rule export

```yaml
rules:
- whens:
  - !<.WhenEventDirection>
    negate: false
    useOrCondition: false
    dataDirection: "Request"
  thens:
  - !<.ThenBuildHttpMessage>
    dataDirection: "Request"
    starterHttpMessage: "{{g:TestHttpPostRequest}}"
    messageValueSetters:
    - destinationMessageValue: "HttpRequestBody"
      destinationIdentifier: ""
      destinationIdentifierPlacement: "Only"
      sourceText: "Test"
    destinationVariableSource: "Event"
    destinationVariableName: "TestRequestBody"
  - !<.ThenLog>
    text: "{{e:TestRequestBody}}"
  enabled: true
  autoRun: true
  name: "Test Dissappearing Post Headers"
webSocketRules: []
variables: []
```
